import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import { Canvas } from "@react-three/fiber";
import Renderer3D from "../components/3d/renderer";
import React, { Suspense } from "react";
import { Container, Row, Col } from 'react-bootstrap';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container fluid>
        <main className={styles.main}>
          <Row>
            <Col md="6" >
              <Canvas style={{ height: "100%", width: "100%" }}>
                <Suspense>
                  <Renderer3D
                    path={'cube.obj'}
                    scale={[1, 1, 1]}
                    position={[0, 0, 0]}
                    renderPriority={2}
                  />
                </Suspense>
              </Canvas>
            </Col>

            <Col md="6">
              <Canvas style={{ height: "100%", width: "100%" }}>
                <Suspense>
                  <Renderer3D
                    path={'cube.obj'}
                    scale={[1, 1, 1]}
                    position={[0, 0, 0]}
                    renderPriority={2}
                  />
                </Suspense>
              </Canvas>
            </Col>

            <Col md="6">
              <Canvas style={{ height: "100%", width: "100%" }}>
                <Suspense>
                  <Renderer3D
                    path={'cube.obj'}
                    scale={[1, 1, 1]}
                    position={[0, 0, 0]}
                    renderPriority={2}
                  />
                </Suspense>
              </Canvas>
            </Col>

            <Col md="6">
              <Canvas style={{ height: "100%", width: "100%" }}>
                <Suspense>
                  <Renderer3D
                    path={'cube.obj'}
                    scale={[1, 1, 1]}
                    position={[0, 0, 0]}
                    renderPriority={2}
                  />
                </Suspense>
              </Canvas>
            </Col>
          </Row>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </Container>
    </div>
  )
}
